"use client"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Navbar from "./navbar"
import { useState } from "react"
import { usePathname } from "next/navigation"

const inter = Inter({ subsets: ["latin"] })
const disableNavbar = ["/login", "/register"]

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [state, setState] = useState(0)
  const pathname = usePathname()
  return (
    <html lang="en">
      <body className={inter.className}>
        {!disableNavbar.includes(pathname) && <Navbar />}
        {/* <div>Ini state di Layout {state}</div>
        <button
          className="bg-blue-300 py-1 px-4 rounded-md ml-2 mb-2"
          onClick={() => setState(state + 1)}
        >
          +
        </button>
        <br />
        <button
          className="bg-blue-300 py-1 px-4 rounded-md ml-2"
          onClick={() => setState(0)}
        >
          reset
        </button> */}
        {children}
      </body>
    </html>
  )
}
